### PR TITLE
bring back PCC public-comments

### LINKED ISSUE #461: keep PCC public-comments open until they are updated
bring back into public-comment section, possibly indicating they are public-comment versions for which the comment period has closed.

```html
<li><a title="Mobile Antepartum Summary (mAPS)" href="./mAPS/index.html">Mobile Antepartum Summary (mAPS) Release 1.0.0-comment</a> - Published 2024-06-04  <i class="fi-web" title="Web Publication"></i><i class="fi-star" title="Implementation Guide"></i></li>
<li><a title="USA - Mobile Antepartum Summary (mAP.usS)" href="../us/PCC/mAPS/index.html">USA Mobile Antepartum Summary (mAPS.us) Release 1.0.0-comment</a> - Published 2024-06-04  <i class="fi-web" title="Web Publication"></i><i class="fi-star" title="Implementation Guide"></i></li>
<li><a title="Occupational Data for Health (ODH)" href="./ODH/index.html">Occupational Data for Health (ODH) Release 1.0.0-comment</a> - Published 2024-03-08  <i class="fi-web" title="Web Publication"></i><i class="fi-star" title="Implementation Guide"></i></li>

```

### PR DESCRIPTION
**Pull request by JohnMoehrke**
Discussed this on the PCC/QRPH call with @afourquet today, and she agreed that these three should still be visible until they are published in updates.

close #461

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@MaryLJ alterntive is to add a new section like public-comment section that holds post public-comment until replaced. But that seemed unnecessary. So I went with easy. What do you think?

**Review by MaryLJ — APPROVED** [review]
Looks, OK.

**Comment by JohnMoehrke** [comment]
Andrea indicates that these will likely be replaced in September

**Comment by MaryLJ** [comment]
> Andrea indicates that these will likely be replaced in September

OK, thank  you.

**Pull request merged**
