### PR TITLE
ITI-18 cleanup

### PR DESCRIPTION
**Pull request by qligier**
This cleans up the ITI-18 profile, as discussed in #138.
Modifications are separated into specific commits to allow cherry-picking, if needed.

What should still be done, in my opinion, is cleaning the lists, they should be nested. The following:
```html
<ol>
    <li class="numbered-list1">Errors shall be returned for the following conditions:</li>
</ol>
<ul>
    <li class="bullet-list2">Unknown query ID (error code XDSUnknownStoredQuery)</li>
</ul>
<ol start="2">
    <li class="numbered-list1">Process the query as appropriate:</li>
</ol>
```
would be better written as:
```html
<ol class="numbered">
    <li>Errors shall be returned for the following conditions:
        <ul class="bullet">
            <li>Unknown query ID (error code XDSUnknownStoredQuery)</li>
        </ul>
    </li>
    <li>Process the query as appropriate:</li>
</ol>
```

Search parameters could also be wrapped in `<var>`.

Feedback welcome.

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
need to resolve merge conflicts.

**Comment by qligier** [comment]
Rebased.

**Comment by JohnMoehrke** [comment]
Note, The changes to the header and footer should not be done. All our pages are using the same header and footer. There might be a need to change things here, but if done, they should be done universally not just to one chapter.   trying to evaluate these is also much harder than evaluating the body of ITI-18.

**Review by JohnMoehrke — COMMENTED** [review]
the quotes thing... is this in our other chapters? Likely something that should be bulk done everywhere. If so, then an issue should be created for this bulk action. It would be okay to do ITI-18 independent of that bulk action, but I don't want to lose a definable bulk edit action opportunity.

**Comment by qligier** [comment]
I've not changed the content of the header and content, just reformatted it except for the xmlns attributes that should be removed everywhere (they've no reason to exist, but that's not an important change).

The quote thing always happen with Word (it automatically replaces straight ones), so yeah, I think it should be checked everywhere.

**Comment by qligier** [comment]
It's #164 and #165.

**Pull request merged**
