### PR TITLE
restore ATNA audit messages away from Gazelle methodology

### LINKED ISSUE #15: replace the changes to ATNA that point at Gazelle, back to inline tables

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #15

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
these four transactions have been restored to the tables as they were prior to November 1, 2020; when I changed them to Gazelle. 

Thus they should be the same as we wanted back then. Not clear if any changes happened between then and now. If there was then those changes need to be discovered and applied to this Pull-Request before it gets accepted.

**Comment by JohnMoehrke** [comment]
@lynnfel can you review and approve?

**Comment by lynnfel** [comment]
Is there a way for me to see the rendered version of the audit tables you restored?

Otherwise, I can assume they're ok...

**Comment by JohnMoehrke** [comment]
unfortunately the github.io pages is no longer able to render our whole profiles site due to the size.

You could clone, which makes a copy of this repository on your computer, and look at your copy with a browser locally.

One worry that I did have was that I am more confident I restored them AS THEY WERE. Just not sure if we made wholesale changes to other ATNA tables that should be made to these. I am not even sure how to detect that. There did not appear to be a need. I was just not sure.

**Comment by lynnfel** [comment]
If you are confident that they are restored as they were, I am not concerned.  It seems we are a couple years past when we did wholesale changes.

**Pull request merged**
