### PR TITLE
clarify FHIR constraint appendix Z

### LINKED ISSUE #227: clarify requirements words
Update appendix Z.10 to
- Point at general Intro E, indicating that there is no intention to conflict with the general conventions IHE has
- Add a sentence indicating that StructureDefinition profiling is the more dominant method of conveying constraints.

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #227

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@lynnfel can you review and approve?

**Comment by lynnfel** [comment]
These FHIR conformance resource mechanism can convey constraints more precicely and in a way that enables testing and real-time validation.
- Fix grammar:  EITHER 'These conformance resource mechanisms can..."   OR "This FHIR conformance resource mechanism can..."
- Fix spelling:  precisely


Sometimes a constraint is less difinitive, such as "Required if known" where the narrative text will call up on the use of "R2". 
- fix spelling:  definitive
- what does this mean: "...where the narrative text will call upon the use of "R2". ???  Do you mean "...where the narrative text will use "R2". ???

**Comment by JohnMoehrke** [comment]
thanks. I will work on these

**Comment by JohnMoehrke** [comment]
@lynnfel I think i addressed your comments. Please review again, and approve if you approve.

**Review by lynnfel — APPROVED** [review]

**Comment by lynnfel** [comment]
wasn't sure whether to delete branch...

**Comment by JohnMoehrke** [comment]
yes, you should delete these branches after merged. No worry if you don't. I can cleanup later.

**Pull request merged**
