### PR TITLE
New addition of the Devices PCIM (HTML) Rev. 2.0 for public comment

### LINKED ISSUE #412: Release DEV/PCIM Rev. 2.0 for PC
Release the Devices PCIM supplement, Rev. 2.0 for public comment. This is an HTML publication.

### PR DESCRIPTION
**Pull request by MaryLJ**
Closes #412 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed
- [x] I have selected a committee co-chair to review the PR

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
would likely be better to have a DEV person approve this. I don't have any way to determine if it is good or not.

**Comment by MaryLJ** [comment]
Yes, thanks, I will make that change now

 

Mary Jungers | Documentation Specialist 

IHE International | IHE.net

**Comment by MaryLJ** [comment]
> I don't see a change to an index.html file to point at this new publication. Is that not needed?

done, thanks

**Comment by eldonmetz** [comment]
> would likely be better to have a DEV person approve this. I don't have any way to determine if it is good or not.

John, how do I get added as a contributor to this repo? I don't see any "Request to join" button.

**Comment by JohnMoehrke** [comment]
> > would likely be better to have a DEV person approve this. I don't have any way to determine if it is good or not.
> 
> John, how do I get added as a contributor to this repo? I don't see any "Request to join" button.

@ToddCooper manages the members of the DEV team. He or some other authority must manage the membership.

**Review by eldonmetz — APPROVED** [review]

**Review by eldonmetz — APPROVED** [review]

**Review by eldonmetz — APPROVED** [review]
Looks good, thank you.

**Review by eldonmetz — APPROVED** [review]

**Comment by MaryLJ** [comment]
Tried numerous time to get the PR approved but maybe a technical glitch is preventing it?? Eldon approved the changes, thus I am merging the branch.

**Comment by MaryLJ** [comment]
Even though this message says the PR was approved, when I go to GitHub it is not, thus I self approved.

 

Mary Jungers | Documentation Specialist 

IHE International | IHE.net

**Pull request merged**
