### PR TITLE
Fix some typos in ITI-18

### PR DESCRIPTION
**Pull request by qligier**
This commit fixes some typos spotted in the ITI-18 specifications.

### CODE REVIEW

**Review by JohnMoehrke — COMMENTED** [review]
looks good. Likely more span can be removed. Would prefer just XMLname class with no span.

**Comment by qligier** [comment]
Sure, I removed only a couple of spans because it introduced white spaces in the quotes, but there's a lot of cleanup that could be done.

**Comment by JohnMoehrke** [comment]
> Sure, I removed only a couple of spans because it introduced white spaces in the quotes, but there's a lot of cleanup that could be done.

Yes, that is what that other issue that you commented on is all about. Cleanup, the transition from WORD to html was messy in ways that are not helpful to maintaining the html. So, this PR is good. but if you want to further refine you can. you could also attack any file and remove unnecessary span under the issue #44.

really appreciate your help.

**Comment by qligier** [comment]
I can spend a bit of time to clean this page. I suggest merging this PR as-is because it was focused on typos; I'll open a new one with the broader cleaning, with each fix in its own commit so it can either be merged as a whole or cherry-picked.

**Comment by JohnMoehrke** [comment]
yes. I agree.  ITI will be meeting on monday to look at these PR

**Comment by JohnMoehrke** [comment]
Committee reviewed and approved

closed #139

**Pull request merged**
