### PR TITLE
update Figure 1:2.1-1

### LINKED ISSUE #398: ITI Volume 1: Figure 2.1-1 is out of date
This diagram should use more abstract concepts rather than specific profile names. Some of these blocks should be removed (PSA).

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #398

## 📑 Description

Update Figure 2.1-1 that shows an overall abstract view of ITI.

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] I have selected a committee co-chair to review the PR

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
The text in chapter 2 introduces this as dependencies among integration profiles. That is not in my new graphic, because that is simply not possible with the portfolio size. 
Should chapter 2 be rewritten to better explain this as an abstract grouping, rather than dependencies?

**Comment by JohnMoehrke** [comment]
Should section 2.2 be removed now that we publish in html and thus it is easier to just click into each? I am worried that the text here is missing newer publications, many of them are just pointing at the specification without summarization, and those with a summary might be out-of-date.

**Comment by MaryLJ** [comment]
> The text in chapter 2 introduces this as dependencies among integration profiles. That is not in my new graphic, because that is simply not possible with the portfolio size. Should chapter 2 be rewritten to better explain this as an abstract grouping, rather than dependencies?

The Volume 1 template was updated a while back and includes changes to Section 2.1. The test is as follows:

2.1	Required Actor Groupings and Bindings
<Important note to editors: when an existing domain is migrating to this new format of the IHE Technical Framework Volume 1, Section 2 from the previous version, entitled “Profile Dependencies”, is deleted. It is absolutely critical that this information is migrated inside each profile in the Required Groupings table. See the Supplement Template Section X.3 for a more detailed explanation of how this is done. If this is a new Technical Framework, this is not an issue.>

The IHE Technical Framework relies on the concepts of required actor groupings and bindings.
Required actor groupings may be defined between two or more IHE actors. Actors are grouped to combine the features of existing actors. This allows reuse of features of an existing actor and does not recreate those same features in another actor. Internal communication between grouped actors is not specified by IHE. An example of grouped actors in the IHE Radiology Scheduled Workflow Profile is the grouping between the Image Manager and Image Archive. 
Additionally, required actor groupings may cross profile boundaries. For example, an XDS Document Registry Actor is required to be grouped with an ATNA Secure Node Actor. Required actor groupings are defined in each profile definition in Volume 1. To comply with an actor in an IHE profile, a system must perform all transactions required for that actor in that profile. Actors supporting multiple Integration Profiles must support all of the transactions of each profile. (Note:  In previous versions of IHE Technical Framework documents, the concept of profile dependencies existed. For simplification, profile dependencies have been combined with required actor groupings and are enumerated/repeated within each profile in Volume 1.)
Bindings refer to content modules. Bindings map data from a content module to the metadata of a specific transport profile. Bindings for content modules, and the associated concepts, are defined in Volume 3.

So I agree, that a rewrite could be done.

**Comment by JohnMoehrke** [comment]
> > The text in chapter 2 introduces this as dependencies among integration profiles. That is not in my new graphic, because that is simply not possible with the portfolio size. Should chapter 2 be rewritten to better explain this as an abstract grouping, rather than dependencies?
> 
> The Volume 1 template was updated a while back and includes changes to Section 2.1. The test is as follows:
> 
> 2.1 Required Actor Groupings and Bindings <Important note to editors: when an existing domain is migrating to this new format of the IHE Technical Framework Volume 1, Section 2 from the previous version, entitled “Profile Dependencies”, is deleted. It is absolutely critical that this information is migrated inside each profile in the Required Groupings table. See the Supplement Template Section X.3 for a more detailed explanation of how this is done. If this is a new Technical Framework, this is not an issue.>
> 
> The IHE Technical Framework relies on the concepts of required actor groupings and bindings. Required actor groupings may be defined between two or more IHE actors. Actors are grouped to combine the features of existing actors. This allows reuse of features of an existing actor and does not recreate those same features in another actor. Internal communication between grouped actors is not specified by IHE. An example of grouped actors in the IHE Radiology Scheduled Workflow Profile is the grouping between the Image Manager and Image Archive. Additionally, required actor groupings may cross profile boundaries. For example, an XDS Document Registry Actor is required to be grouped with an ATNA Secure Node Actor. Required actor groupings are defined in each profile definition in Volume 1. To comply with an actor in an IHE profile, a system must perform all transactions required for that actor in that profile. Actors supporting multiple Integration Profiles must support all of the transactions of each profile. (Note: In previous versions of IHE Technical Framework documents, the concept of profile dependencies existed. For simplification, profile dependencies have been combined with required actor groupings and are enumerated/repeated within each profile in Volume 1.) Bindings refer to content modules. Bindings map data from a content module to the metadata of a specific transport profile. Bindings for content modules, and the associated concepts, are defined in Volume 3.
> 
> So I agree, that a rewrite could be done.

should we do that now? In this PR?

**Comment by MaryLJ** [comment]
> Should section 2.2 be removed now that we publish in html and thus it is easier to just click into each? I am worried that the text here is missing newer publications, many of them are just pointing at the specification without summarization, and those with a summary might be out-of-date.

The Volume 1 template simply includes the following:

2.3	Profiles Overview
A brief overview of each <Domain Name> profile is provided on the IHE Wiki at https://wiki.ihe.net/index.php/Profiles.

It also includes a Section 2.4
2.4	Product Implementations
As described in detail in the [IHE Technical Frameworks General Introduction](https://profiles.ihe.net/GeneralIntro/index.html), an implementer chooses specific profiles, actors, and options to implement for their product. To comply with an actor in an IHE profile, a system must perform all the required transactions for that actor in that profile. 
To communicate the conformance of a product offering with IHE profiles, implementers provide an IHE Integration Statement describing which IHE integration profiles, IHE actors and options are incorporated. 
Further discussion about integration statements and a sample form can be found in the IHE Technical Frameworks General Introduction, [Appendix F](https://profiles.ihe.net/GeneralIntro/ch-F.html). To make consumers aware of the product integration statement, enter it in the IHE Product Registry (http://product-registry.ihe.net/).

I think we could update the ITI Volume 1 Section 2 to match the current template and that would address your concerns.

The template is located at https://drive.google.com/drive/u/0/folders/13jyh22oXwgfD-plpZhSVpCatHSoFqqFu

**Comment by JohnMoehrke** [comment]
@MaryLJ I have aligned chapter 2 in this pull-request. Please review. I would like to include this pull-request in upcoming publication.

**Review by MaryLJ — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
