### PR TITLE
update XDM and DSUB to indicate supplements

### LINKED ISSUE #435: ITI indicate supplements
I noticed that DEN updates XDM, but it is not mentioned at the beginning of XDM.
I noticed that DUBm updates DSUB, but it is not mentioned.

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #435

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@MaryLJ please review and approve

**Review by MaryLJ — COMMENTED** [review]
The link in the XDM entry is to the DEN supplement <a href="https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_DEN.pdf">Document Encryption (DEN)</a>

**Comment by JohnMoehrke** [comment]
> The link in the XDM entry is to the DEN supplement [Document Encryption (DEN)](https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_DEN.pdf)

Yes, because the DEN supplement adds an option to XDM.

**Comment by MaryLJ** [comment]
> > The link in the XDM entry is to the DEN supplement [Document Encryption (DEN)](https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_DEN.pdf)
> 
> Yes, because the DEN supplement adds an option to XDM.

OK, thank you. I will approve.

**Review by MaryLJ — APPROVED** [review]
Looks OK.

**Pull request merged**
