### PR TITLE
Release BALP 1.1.2

### LINKED ISSUE #317: BALP update

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #317

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
This is needed in the first wave. I am NOW putting this publication on the Website, but not updating the index.html. We should update the index.html on Friday with all of them. This needs to go onto the web site to enable the second wave to build depending on this.

**Comment by JohnMoehrke** [comment]
Mary, please approve.

**Comment by MaryLJ** [comment]
Approved

**Review by MaryLJ — APPROVED** [review]
Approve

**Pull request merged**
