### PR TITLE
add links where to submit public comments

### LINKED ISSUE #259: Add links for public comment submission to SDPi index
Add links for public comment submission to SDPi index

### PR DESCRIPTION
**Pull request by MaryLJ**
Closes #259 

## 📑 Description

Add links where to submit public comments to the SDPi index file

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [x] I have selected a committee co-chair to review the PR

### CODE REVIEW

**Review by ToddCooper — APPROVED** [review]
Reviewed the change and approve.

**Comment by ToddCooper** [comment]
@MaryLJ  - I approved the change ... thanks! ... and assume that that should be enough given the need for one reviewer.  But apparently not OR perhaps you needed approval from someone that is on the Publications repo "team"?

**Comment by MaryLJ** [comment]
Thanks. Yes, it appears that way

 

“ At least 1 approving review is required by reviewers with write access”

 

Mary

**Review by JohnMoehrke — APPROVED** [review]

**Comment by JohnMoehrke** [comment]
sorry for the delay, travel day

**Pull request merged**
