### PR TITLE
Update ch-4.2.html for 2023 CP integration in Vol 3

### LINKED ISSUE #297: Integrate approved ITI CPs into Volume 3
CP integrated in Vol 3:
1273-03
1277-03
1269-03
1219-04
1283-00

### PR DESCRIPTION
**Pull request by gpavan19**
CP integrated in Vol 3:
1273-03
1277-03
1269-03
1219-04
1283-00
1260-03

Closes #297 

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] I have selected a committee co-chair to review the PR

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@gpavan19 I noticed that there is a Volume 3 change in CP 1260. Can you add that change to this pull-request?

**Comment by slagesse-epic** [comment]
Also @gpavan19 please take a look at the small additional change I made for CP-ITI-1219 that I believe was missed.

**Comment by gpavan19** [comment]
@JohnMoehrke @slagesse-epic I have added the CP-ITI-1260 change

Also @slagesse-epic I confirm that I missed that little change from CP-ITI-1219. Great catch, thanks!

**Review by slagesse-epic — APPROVED** [review]
Looks good.

**Pull request merged**
