### PR TITLE
release IUA 2.3

### LINKED ISSUE #422: Release IUA 2.3
CP integration

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #422

### CODE REVIEW

**Comment by MaryLJ** [comment]
Hi. I have a PR to submit on this which I will do in a moment.

**Comment by JohnMoehrke** [comment]
Oh. You are not done with the source... okay


John Moehrke - Architect: Standards - Interoperability, Privacy, and
Security for Bylight.com
https://healthcaresecprivacy.blogspot.com

**Comment by MaryLJ** [comment]
I am but did not submit PR because I had a question about the
capitalization of the normative words. After you answered I just didn't
submit PR right away.

**Comment by JohnMoehrke** [comment]
@MaryLJ this now has your improvements, and is ready for approval.

**Review by MaryLJ — APPROVED** [review]
approve

**Pull request merged**
