### PR TITLE
PCC release of mAPS

### LINKED ISSUE #424: Release for Public-Comment PCC.mAPS 1.0.0-comment

### LINKED ISSUE #425: Release for Public-Comment PCC.mAPS.us version 1.0.0-comment
Note we will try this in a US realm folder
https://profiles.ihe.net/US/PCC/mAPS.us

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #424 
close #425

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@MaryLJ here is a DRAFT pull-request. You will see that I drafted up the changes for the index.html. Note the content is not there yet.

I am concerned that the previous public comments are still there, but didn't want to remove them.

**Comment by JohnMoehrke** [comment]
mAPS international is now here

**Comment by MaryLJ** [comment]
> @MaryLJ here is a DRAFT pull-request. You will see that I drafted up the changes for the index.html. Note the content is not there yet.
> 
> I am concerned that the previous public comments are still there, but didn't want to remove them.

I think it is OK to remove them as the comment period is over.

**Comment by MaryLJ** [comment]
Changes “this” to “these” and “document” to “documents”

 

Comments on this document should be submitted by July 4, 2024.

 

Mary Jungers | Documentation Specialist 

IHE International | IHE.net

**Comment by JohnMoehrke** [comment]
ready for approval and deployment

**Review by MaryLJ — APPROVED** [review]
approved

**Pull request merged**
