### PR TITLE
Prototype release for ITI.DSGj Supplement

### LINKED ISSUE #429: Release DSG JSON Supplement for Public-Comment

### PR DESCRIPTION
**Pull request by JohnMoehrke**
Public-Comment for DSGj Supplement. 
close #429

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
Mary,  This pull-request is using the current and approved DSGj files. You could review this to see what we will publish. But if you find anything to fix. you would need to fix that in the ITI.DSGj repo. okay?

**Comment by JohnMoehrke** [comment]
@mary, this now has your updates to the ITI.DSGj repo. It should be ready to merge in for publication. Please review and approve.

**Comment by MaryLJ** [comment]
I see a missed period at the end of a sentence that I added. I will create an issue to fix this at TI publication.

 

 

Mary Jungers | Documentation Specialist 

IHE International | IHE.net

**Review by MaryLJ — APPROVED** [review]
Approve for publication

**Pull request merged**
