### PR TITLE
fix delayed doc hash (and a QA issue)

### LINKED ISSUE #129: Delayed Document Assembly vol 1 and 2 conflict on hash value
Volume 1 says hash and size are 0
Volume 2 says size is 0, and hash is the valid hash value of a zero length file.

Recommend that Volume 1 be fixed, as this solution allows hash to always be calculated properly.

https://profiles.ihe.net/ITI/TF/Volume1/ch-10.html#10.2.10

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #129

### CODE REVIEW

**Comment by lynnfel** [comment]
[This CP](https://docs.google.com/document/d/1JB87H32043GEWIH-DXkYGFJMfFBqBZUc/edit?usp=sharing&ouid=105005564211348147894&rtpof=true&sd=true) was added to Incoming and to the ITI CP processing agenda for Apr 12.   Resolution of this GitHub issue depends on what ITI Tech decides to do with that CP.  (If the CP is accepted, the link will change.  )

**Comment by JohnMoehrke** [comment]
CP-ITI-1278

**Comment by JohnMoehrke** [comment]
Seems this did pass ballot-61
Possibly this is the right solution -- https://docs.google.com/document/d/1xVMyIFL-K6RX-K7L5vJo-e5ImsYl_h_E/edit

If so, then need to align this PR with that result

**Comment by JohnMoehrke** [comment]
I updated the first paragraph in 10.2.10 because it was still saying 0/0.

**Comment by lynnfel** [comment]
For the purpose of documentation, the Final Text version of the CP is CP-ITI-1278-02 (not -01 as linked above).  A direct link to the CP in the Final Text folder is https://docs.google.com/document/d/1JfwE0FIWNpqlIYl8AqL2lcbLsx89CvW2/edit?usp=share_link&ouid=105005564211348147894&rtpof=true&sd=true

**Comment by JohnMoehrke** [comment]
I have adjusted to the 02 Volume 1. Thanks for finding this.

**Comment by JohnMoehrke** [comment]
@lynnfel please review and approve if you approve

**Review by lynnfel — APPROVED** [review]

**Pull request merged**
