### PR TITLE
Integrate CP-ITI-1253-06

### PR DESCRIPTION
**Pull request by lynnfel**
Vol 3 CP 1253 integration ready for you to review.

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
looks good to me.

**Review by slagesse-epic — COMMENTED** [review]
It looks like CP-ITI-1270 was not properly integrated in #143 . DocumentEntry.patientId should link to section 4.2.3.**2**.16 rather than 4.2.3.**1**.16, and DocumentEntry.uniqueId should link to section 4.2.3.**2.**.26 rather than 4.2.3.**1**.26. 

Should we fix that in this branch?

**Comment by JohnMoehrke** [comment]
this should be ready to merge. right?

**Comment by lynnfel** [comment]
Yes, I think this is ready to merge

**Pull request merged**
